### ISSUE TITLE
What is the compenents of the mixed audio files and how to generate the mixed files?

### ISSUE THREAD

**Issue by OlivierX** [hbenbel/FastICA#1]
Hello, it's a nice and brief implementation of FastICA, I wonder to know it better! Well, it seems that each mixed audio file is concatenated by several different source, but the algorithme do once FastICA to them for one analyse of compenents. Isn't the algorithme designed for the problem like cocktail party ? So the input is supposed to be single, right?

**Comment by hbenbel** [comment]
Hello! Sorry for the late response. Yes you are right. I think the confusion comes from the fact that for the example data I used 9 different files as input and there is 9 different sources but technically you can set the nsources parameter to 1 and the ncomponents parameter to as many as you want. Note that the example data is composed of 9 wav files coming from the same scene but taken with 9 different mics. Having this kind of configuration helps having good results for the ICA. You can still give as input only one file it should work although the results might be quite bad. I invite you to test the results with a fixed ncomponents=9 and different nsources (1,2,3,...9) you will see that the quality of the results increases with the number of mixed sources used
